version: 0.2

phases:
  install:
    commands:
      - npm i npm@latest -g
      - npm install -g pnpm
  pre_build:
    commands:
      - echo Installing node packages
      - pnpm install
  build:
    commands:
      - echo Building...
      - pnpm build
  post_build:
    commands:
      - echo Build Complete